### ISSUE TITLE
Fail2Ban v0.9.6 don't start with apache-proxy filter

### ISSUE THREAD

**Issue by alex24777** [fail2ban/fail2ban-publications#1]
Debian 9
the Fail2Ban v0.9.6 don't start with
recommended in https://www.fail2ban.org/wiki/index.php/HOWTO_apache_proxy_filter apache-proxy filter
failregex = ^(?:(?![0-9\.]* - - \[.*\] "([A-Z]* /.* HTTP/1\.[0-9]|-)")<HOST>)

Debian 8
Fail2Ban v0.8.13
Fail2Ban  with the same filter is startinf and working correctly

**Comment by yarikoptic** [comment]
this repository has nothing to do with troubleshooting fail2ban
